guacd:
  address: 127.0.0.1:4822
  override: true
log:
  level: INFO
server:
  api:
    ids: true
    list: true
    read: true
    delete: true
    update: true
  auth:
    basic:
      username: guac
      password: guac
      realm: Guac Server
    header:
      name: X-Forwarded-User
      values: []
  static:
    path: ./static
conns:
- access: guac
  hostname: 192.168.1.1
  id: ssh-192.168.1.1-22-root
  ignore-cert: "true"
  password: "111222"
  port: "22"
  scheme: ssh
  username: root